services:
  # Backend service
  - type: web
    name: qguideguide-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python scripts/warm_cache.py  # Warm the cache during deployment
    startCommand: gunicorn core.wsgi:application
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
