services:
  # Backend service
  - type: web
    name: qguideguide-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false

  # Frontend service
  - type: static
    name: qguideguide-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/dist
    env:
      - key: VITE_API_URL
        value: https://qguideguide.onrender.com
