services:
  - type: web
    name: qguideguide
    env: python
    buildCommand: |
      # Build frontend
      cd frontend
      npm install
      npm run build
      cd ../backend
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
    startCommand: cd backend && gunicorn core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
