# Generated by Django 5.1.3 on 2024-11-16 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('blue_course_id', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_tables', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raters', models.CharField(blank=True, max_length=255, null=True)),
                ('students', models.CharField(blank=True, max_length=255, null=True)),
                ('statistics', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('options', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('excellent', models.CharField(blank=True, max_length=50, null=True)),
                ('very_good', models.CharField(blank=True, max_length=50, null=True)),
                ('good', models.CharField(blank=True, max_length=50, null=True)),
                ('fair', models.CharField(blank=True, max_length=50, null=True)),
                ('unsatisfactory', models.CharField(blank=True, max_length=50, null=True)),
                ('course_mean', models.FloatField(blank=True, null=True)),
                ('fas_mean', models.FloatField(blank=True, null=True)),
                ('instructor_mean', models.FloatField(blank=True, null=True)),
                ('feedback_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='courses.feedbacktable')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.instructor'),
        ),
    ]
