# Generated by Django 5.1.3 on 2024-11-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='response_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='response_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='students_enrolled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktable',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
