# Generated by Django 5.1.3 on 2024-12-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='accessible_mean_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='assignments_mean_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_mean_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='discussion_mean_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='effective_mean_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='enthusiasm_mean_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='feedback_mean_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='hours_mean_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='inst_feedback_mean_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor_mean_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='materials_mean_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='recommend_mean_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='response_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='returns_mean_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='section_mean_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursefeedbackquestion',
            name='course_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursefeedbackquestion',
            name='fas_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoursandrecquestion',
            name='mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoursandrecquestion',
            name='median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoursandrecquestion',
            name='mode',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoursandrecquestion',
            name='response_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoursandrecquestion',
            name='standard_dev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructorfeedbackquestion',
            name='fas_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructorfeedbackquestion',
            name='instructor_mean',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
