# Generated by Django 5.1.3 on 2024-11-17 22:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_response_count_course_response_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseRatingBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excellent_count', models.IntegerField(default=0)),
                ('very_good_count', models.IntegerField(default=0)),
                ('good_count', models.IntegerField(default=0)),
                ('fair_count', models.IntegerField(default=0)),
                ('unsatisfactory_count', models.IntegerField(default=0)),
                ('course_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('fas_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('instructor_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedbackentry',
            name='feedback_table',
        ),
        migrations.RemoveField(
            model_name='feedbacktable',
            name='course',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-term', 'department', 'title']},
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='course',
            name='overall_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='course',
            name='workload_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='course',
            name='would_recommend_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='response_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(choices=[('2019 Fall', '2019 Fall'), ('2020 Fall', '2020 Fall'), ('2021 Spring', '2021 Spring'), ('2021 Fall', '2021 Fall'), ('2022 Spring', '2022 Spring'), ('2022 Fall', '2022 Fall'), ('2023 Spring', '2023 Spring'), ('2023 Fall', '2023 Fall')], max_length=100),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department'], name='courses_cou_departm_9688c2_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['term'], name='courses_cou_term_398537_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['overall_score'], name='courses_cou_overall_b4a382_idx'),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseratingbreakdown',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_breakdown', to='courses.course'),
        ),
        migrations.DeleteModel(
            name='FeedbackEntry',
        ),
        migrations.DeleteModel(
            name='FeedbackTable',
        ),
    ]
