# Generated by Django 5.1.3 on 2024-11-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursecomment_courseratingbreakdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseratingbreakdown',
            name='excellent_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='courseratingbreakdown',
            name='fair_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='courseratingbreakdown',
            name='good_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='courseratingbreakdown',
            name='unsatisfactory_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='courseratingbreakdown',
            name='very_good_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
