# Generated by Django 5.1.3 on 2024-12-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseratingbreakdown_excellent_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='response_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='response_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_enrolled',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='would_recommend_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='courseratingbreakdown',
            name='excellent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courseratingbreakdown',
            name='fair_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courseratingbreakdown',
            name='good_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courseratingbreakdown',
            name='unsatisfactory_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courseratingbreakdown',
            name='very_good_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
