# Generated by Django 5.1.3 on 2024-12-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_instructor_alter_course_response_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='blue_course_id',
            field=models.CharField(max_length=100),
        ),
    ]
