# Generated by Django 5.1.3 on 2024-12-04 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_blue_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('excellent_count', models.IntegerField(default=0)),
                ('very_good_count', models.IntegerField(default=0)),
                ('good_count', models.IntegerField(default=0)),
                ('fair_count', models.IntegerField(default=0)),
                ('unsatisfactory_count', models.IntegerField(default=0)),
                ('course_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('fas_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('instructor_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoursAndRecQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_count', models.IntegerField(default=0)),
                ('response_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('mean', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('median', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('mode', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('standard_dev', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseratingbreakdown',
            name='course',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_departm_9688c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_term_398537_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_overall_b4a382_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='difficulty_rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='course',
            name='response_count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='response_rate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students_enrolled',
        ),
        migrations.RemoveField(
            model_name='course',
            name='workload_rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='would_recommend_percent',
        ),
        migrations.AddField(
            model_name='course',
            name='accessible_mean_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='assignments_mean_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_mean_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='discussion_mean_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='effective_mean_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enthusiasm_mean_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='feedback_mean_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hours_mean_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='inst_feedback_mean_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_mean_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='invited_responses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='materials_mean_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='number_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='recommend_mean_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='response_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='responses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='returns_mean_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='section_mean_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='feedbackquestion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_questions', to='courses.course'),
        ),
        migrations.AddField(
            model_name='hoursandrecquestion',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hours_breakdown', to='courses.course'),
        ),
        migrations.DeleteModel(
            name='CourseRatingBreakdown',
        ),
    ]
