# Generated by Django 5.1.3 on 2024-12-06 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_feedbackquestion_hoursandrecquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('excellent_count', models.IntegerField(default=0)),
                ('very_good_count', models.IntegerField(default=0)),
                ('good_count', models.IntegerField(default=0)),
                ('fair_count', models.IntegerField(default=0)),
                ('unsatisfactory_count', models.IntegerField(default=0)),
                ('course_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('fas_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_feedback_questions', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorFeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('excellent_count', models.IntegerField(default=0)),
                ('very_good_count', models.IntegerField(default=0)),
                ('good_count', models.IntegerField(default=0)),
                ('fair_count', models.IntegerField(default=0)),
                ('unsatisfactory_count', models.IntegerField(default=0)),
                ('fas_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('instructor_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_feedback_questions', to='courses.course')),
            ],
        ),
        migrations.DeleteModel(
            name='FeedbackQuestion',
        ),
    ]
