# Generated by Django 5.1.3 on 2024-12-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_accessible_mean_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='accessible_mean_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='accessible_mean_grade_department',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='accessible_mean_rating_bayesian_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='accessible_mean_rating_bayesian_score_department',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='assignments_mean_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='assignments_mean_grade_department',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='assignments_mean_rating_bayesian_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='assignments_mean_rating_bayesian_score_department',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_mean_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_mean_grade_department',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_mean_rating_bayesian_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_mean_rating_bayesian_score_department',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='discussion_mean_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='discussion_mean_grade_department',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='discussion_mean_rating_bayesian_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='discussion_mean_rating_bayesian_score_department',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='effective_mean_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='effective_mean_grade_department',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='effective_mean_rating_bayesian_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='effective_mean_rating_bayesian_score_department',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enthusiasm_mean_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enthusiasm_mean_grade_department',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enthusiasm_mean_rating_bayesian_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enthusiasm_mean_rating_bayesian_score_department',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='feedback_mean_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='feedback_mean_grade_department',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='feedback_mean_rating_bayesian_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='feedback_mean_rating_bayesian_score_department',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='inst_feedback_mean_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='inst_feedback_mean_grade_department',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='inst_feedback_mean_rating_bayesian_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='inst_feedback_mean_rating_bayesian_score_department',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_mean_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_mean_grade_department',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_mean_rating_bayesian_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_mean_rating_bayesian_score_department',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='materials_mean_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='materials_mean_grade_department',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='materials_mean_rating_bayesian_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='materials_mean_rating_bayesian_score_department',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='recommend_mean_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='recommend_mean_grade_department',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='recommend_mean_rating_bayesian_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='recommend_mean_rating_bayesian_score_department',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='returns_mean_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='returns_mean_grade_department',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='returns_mean_rating_bayesian_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='returns_mean_rating_bayesian_score_department',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='section_mean_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='section_mean_grade_department',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='section_mean_rating_bayesian_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='section_mean_rating_bayesian_score_department',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
