# Generated by Django 5.1.3 on 2024-12-30 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_accessible_mean_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='recommend_mean_grade',
        ),
        migrations.RemoveField(
            model_name='course',
            name='recommend_mean_grade_department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='recommend_mean_rating_bayesian_score',
        ),
        migrations.RemoveField(
            model_name='course',
            name='recommend_mean_rating_bayesian_score_department',
        ),
    ]
