# Generated by Django 5.1.3 on 2025-01-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_recommend_mean_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
