# Generated by Django 5.1.3 on 2025-01-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_department_alter_course_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
