# Generated by Django 5.1.3 on 2025-01-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_mean_rating',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='responses',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(choices=[('2019 Fall', '2019 Fall'), ('2020 Fall', '2020 Fall'), ('2021 Spring', '2021 Spring'), ('2021 Fall', '2021 Fall'), ('2022 Spring', '2022 Spring'), ('2022 Fall', '2022 Fall'), ('2023 Spring', '2023 Spring'), ('2023 Fall', '2023 Fall')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title', 'department', 'instructor'], name='courses_cou_title_33861a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_mean_rating', 'responses'], name='courses_cou_course__9b9613_idx'),
        ),
    ]
