# Generated by Django 5.1.3 on 2025-01-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_course_mean_rating_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_title_33861a_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_course__9b9613_idx',
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['term', 'department', 'instructor'], name='courses_cou_term_af7331_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_mean_rating', 'department'], name='courses_cou_course__c78396_idx'),
        ),
    ]
