# Generated by Django 5.1.3 on 2025-01-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('mean_empirical_bayes_average', models.FloatField(default=0.0)),
                ('mean_empirical_bayes_rank', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='departments',
        ),
        migrations.AddField(
            model_name='professor',
            name='departments',
            field=models.ManyToManyField(related_name='professors', to='professors.department'),
        ),
    ]
