# Generated by Django 5.1.3 on 2025-01-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_department_remove_professor_departments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={},
        ),
        migrations.RemoveField(
            model_name='department',
            name='mean_empirical_bayes_average',
        ),
        migrations.RemoveField(
            model_name='department',
            name='mean_empirical_bayes_rank',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='departments',
        ),
        migrations.AddField(
            model_name='department',
            name='empirical_bayes_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='empirical_bayes_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='empirical_bayes_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='empirical_bayes_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='intra_department_eb_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='intra_department_letter_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='intra_department_ranks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='overall_letter_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='total_ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
