# Generated by Django 5.1.3 on 2025-01-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_alter_professor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='department',
        ),
        migrations.AddField(
            model_name='professor',
            name='departments',
            field=models.ManyToManyField(related_name='professors', to='professors.department'),
        ),
    ]
