# Generated by Django 5.1.3 on 2025-01-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0006_alter_department_empirical_bayes_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='departments',
        ),
        migrations.AddField(
            model_name='professor',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='empirical_bayes_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
