# Generated by Django 5.1.3 on 2025-01-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0007_remove_professor_departments_professor_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='department',
            new_name='departments',
        ),
    ]
