# Generated by Django 5.1.3 on 2025-01-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0008_rename_department_professor_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
