# Generated by Django 5.1.3 on 2025-01-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0009_professor_modified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='intra_department_eb_average',
            new_name='intra_department_metrics',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='intra_department_letter_grade',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='intra_department_ranks',
        ),
    ]
