# Generated by Django 5.1.3 on 2025-01-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0010_rename_intra_department_eb_average_professor_intra_department_metrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='intra_department_metrics',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
