# Generated by Django 5.1.3 on 2025-01-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0011_alter_professor_intra_department_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='professor_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
